DATA SEGMENT
A DB 5
DATA ENDS
CODE SEGMENT
      ASSUME DS:DATA,CS:CODE
START:
      MOV AX,DATA
      MOV DS,AX
      MOV AH,00
      MOV AL,A
      MUL A
      MOV BL,AL
      MUL WORD PTR A
      MOV BH,AL
      MOV AX,4CH
      INT 21H
CODE ENDS
END START